import { Project } from './types';

export const PROJECTS: Project[] = [
  {
    id: 1,
    title: 'Divine King',
    description: 'Discover the leading Chemical Company in the Philippines for Organic Chemicals and Modern Pest Control Equipment in Divine King.',
    imageUrl: '/assets/img/divineking.jpg',
    liveUrl: 'https://divineking.com/',
    tags: [],
  },
  {
    id: 2,
    title: 'First Fil-Bio',
    description: 'Discover top-quality veterinary pharmaceutical products and diagnostic services for poultry and swine at First Fil-Bio.',
    imageUrl: '/assets/img/firstfilbio.jpg',
    liveUrl: 'https://firstfilbio.com/',
    tags: [],
  },
  {
    id: 3,
    title: 'Actuate Builder',
    description: 'A one-stop shop Design and Build Firm providing Architectural Design and Construction Services throughout the Philippines.',
    imageUrl: '/assets/img/actuate_builder.jpg',
    liveUrl: 'https://abi-ph.com/',
    tags: [],
  },
  {
    id: 4,
    title: 'Bonavita',
    description: "Bonavita Philippines aims to improve people's way of life and give people the opportunity to do good work as well.",
    imageUrl: '/assets/img/bonavita.jpg',
    liveUrl: 'https://bonavita.ph/',
    tags: [],
  },
  {
    id: 5,
    title: 'TCG',
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam voluptates quam veritatis nostrum nesciunt dolor minima alias, illo qui recusandae.',
    imageUrl: '/assets/img/tcg.jpg',
    liveUrl: 'https://tcg.ph/',
    tags: [],
  },
  {
    id: 6,
    title: 'PDAX',
    description: 'Buy, sell, and trade the world’s top cryptocurrencies at competitive market rates.',
    imageUrl: '/assets/img/pdax.jpg',
    liveUrl: 'https://pdax.ph/',
    tags: [],
  },
  {
    id: 7,
    title: 'Ocfireworks',
    description: "Buy wholesale fireworks online At Overstock Central Fireworks: America's Fireworks Superstore. Free shipping and financing available.",
    imageUrl: '/assets/img/ocfireworks.jpg',
    liveUrl: 'https://ocfireworks.innovnational.com/',
    tags: [],
  },
  {
    id: 8,
    title: 'Mosaic Solution',
    description: 'Find the top POS supplier in the Philippines for your business needs. Get reliable, efficient, and affordable point-of-sale solutions today!',
    imageUrl: '/assets/img/mosaic.jpg',
    liveUrl: 'https://www.mosaic-solutions.com/',
    tags: [],
  },
  {
    id: 9,
    title: 'Flasked',
    description: "Quench your thirst with Flasked's wide selection of alcoholic and non-alcoholic beverages with the best prices and instant delivery.",
    imageUrl: '/assets/img/flasked.jpg',
    liveUrl: 'https://www.flasked.ph/',
    tags: [],
  },
  {
    id: 10,
    title: 'Chevrolet Philippines',
    description: 'The exclusive importer and distributor of Chevrolet vehicles and parts in the Philippines!',
    imageUrl: '/assets/img/chevrolet.jpg',
    liveUrl: 'https://chevrolet.com.ph/',
    tags: [],
  },
  {
    id: 11,
    title: 'Shang Summit',
    description: 'Luxury living in South Triangle, Quezon City with soaring panoramic views, exquisite interiors, and world-class amenities.',
    imageUrl: '/assets/img/shang-summit.jpg',
    liveUrl: 'https://shangsummit.com',
    tags: [],
  },
  {
    id: 12,
    title: 'Gus Tambunting - Official Website',
    description: "Check Congressman Gus Tambunting's projects and advocacies, serving Parañaque City with dedication and public service.",
    imageUrl: '/assets/img/gustambunting.jpg',
    liveUrl: 'https://gustambunting.com/',
    tags: [],
  },
  {
    id: 13,
    title: 'Bank of Makati',
    description: 'With 60+ years of trusted service, we’re committed to empowering MSMEs and shaping the future of banking.',
    imageUrl: '/assets/img/bankofmakati.jpg',
    liveUrl: 'https://bankofmakati.innovnational.com/',
    tags: [],
  },
   {
    id: 13,
    title: 'Sparkyes',
    description: 'Ignite growth with SPARK—subscription-based, data-driven coaching and learning for multi-generational teams to boost culture, performance, and success.',
    imageUrl: '/assets/img/sparkyes.jpg',
    liveUrl: 'https://sparkyes.innovnational.com',
    tags: [],
  },
];
